[package]
name = "dots"
version = "0.1.0"
edition = "2021"
description = "CLI for managing dot-files."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.1", features = ["derive", "env"] }
colored = "2.0.0"
